# Generated by Django 5.0 on 2024-02-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_delete_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
