# Generated by Django 5.0 on 2024-02-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_book_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='cover',
        ),
    ]
